export const LOGIN_ROUTE = '/login'
export const TEST_ROUTE = '/test'
export const HOME_ROUTE = '/'
export const SECTION_A_ROUTE = '/sectionA'
export const SECTION_B1_ROUTE = '/sectionB1'
export const LEARN_ROUTE = '/learn'
